"""
data_science_routes.py

New API endpoints for the geospatial clustering + risk scoring feature.
Designed as a separate FastAPI APIRouter so it can be added to your
existing main.py with just 2 extra lines, without touching existing code.

Place this file in your `backend/` folder, alongside main.py.
Also place: risk_model.joblib, cluster_summary.json (generated by the
clustering.py / risk_model.py scripts) in the same backend/ folder.
"""

import json
import numpy as np
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
import joblib
import os

router = APIRouter(prefix="/api/v1/ds", tags=["data-science"])

EARTH_RADIUS_KM = 6371.0088
MODEL_PATH = os.path.join(os.path.dirname(__file__), "risk_model.joblib")
CLUSTERS_PATH = os.path.join(os.path.dirname(__file__), "cluster_summary.json")

_model_bundle = None
_clusters = None


def _load_artifacts():
    """Lazy-load the trained model + cluster data once, on first request."""
    global _model_bundle, _clusters
    if _model_bundle is None:
        _model_bundle = joblib.load(MODEL_PATH)
    if _clusters is None:
        with open(CLUSTERS_PATH) as f:
            _clusters = json.load(f)
    return _model_bundle, _clusters


def haversine_km(lat1, lng1, lat2, lng2):
    lat1, lng1, lat2, lng2 = map(np.radians, [lat1, lng1, lat2, lng2])
    dlat = lat2 - lat1
    dlng = lng2 - lng1
    a = np.sin(dlat / 2) ** 2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlng / 2) ** 2
    return 2 * EARTH_RADIUS_KM * np.arcsin(np.sqrt(a))


class RiskScoreQuery(BaseModel):
    latitude: float
    longitude: float
    hour: int | None = None  # optional; defaults to current server hour if omitted


@router.get("/clusters")
async def get_clusters():
    """Return all identified high-risk zones (from offline DBSCAN clustering)."""
    try:
        _, clusters = _load_artifacts()
    except FileNotFoundError:
        raise HTTPException(
            status_code=503,
            detail="Clustering artifacts not found. Run clustering.py and risk_model.py first."
        )
    return {"zone_count": len(clusters), "zones": clusters}


@router.post("/risk-score")
async def get_risk_score(query: RiskScoreQuery):
    """
    Predict a real-time risk tier (low/medium/high) for a given location,
    using the trained RandomForest model. This is what the chatbot or
    frontend map can call to show contextual risk information.
    """
    try:
        bundle, clusters = _load_artifacts()
    except FileNotFoundError:
        raise HTTPException(
            status_code=503,
            detail="Risk model not found. Run clustering.py and risk_model.py first."
        )

    model = bundle["model"]
    feature_cols = bundle["feature_cols"]

    import datetime
    hour = query.hour if query.hour is not None else datetime.datetime.utcnow().hour

    if clusters:
        dists = [haversine_km(query.latitude, query.longitude, c["centroid_lat"], c["centroid_lng"]) for c in clusters]
        dist_to_nearest = min(dists)
        nearest_zone = clusters[int(np.argmin(dists))]
    else:
        dist_to_nearest = 999.0
        nearest_zone = None

    import pandas as pd
    features = pd.DataFrame([[query.latitude, query.longitude, hour, dist_to_nearest]], columns=feature_cols)
    prediction = model.predict(features)[0]
    probabilities = dict(zip(model.classes_, model.predict_proba(features)[0].round(3)))

    return {
        "risk_tier": prediction,
        "confidence": probabilities,
        "distance_to_nearest_known_zone_km": round(dist_to_nearest, 3),
        "nearest_zone": nearest_zone["dominant_zone_hint"] if nearest_zone else None,
        "queried_hour": hour,
    }