services:
  - type: web
    name: kanyarakshak-core
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: BASE_URL
        value: https://kanyarakshak-core.onrender.com